# Numpy exercises

1. Import the numpy package under the name np

 hint: import … as

In [4]:
import numpy as np

Create a null vector of size 10 

hint: np.zeros

In [6]:
null_vector = np.zeros(10)

print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Create a null vector of size 10 but the fifth value which is 1

hint: array[4]

In [7]:
null_vector = np.zeros(10)

null_vector[4] = 1

print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Create a vector with values ranging from 10 to 49

hint: arange

In [9]:
vector = np.arange(10, 50)

print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Create a 3x3 matrix with values ranging from 0 to 8

hint: reshape

In [ ]:
matrix = np.arange(9).reshape(3, 3)

print(matrix)


Find indices of non-zero elements from [1,2,0,0,4,0]

hint: np.nonzero

In [14]:
elements = [1, 2, 0, 0, 4, 0]

arr = np.array(elements)

non_zero = np.nonzero(arr)

print(non_zero)


(array([0, 1, 4]),)


Create a 3x3 identity matrix

hint: np.eye

In [15]:
identity_matrix = np.eye(3)

print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Create a 3x3x3 array with random values

hint: np.random.random

In [16]:
array = np.random.random((3, 3, 3))

print(array)

[[[0.39622581 0.7239349  0.12038639]
  [0.7645336  0.31822388 0.57296173]
  [0.03343139 0.30023186 0.25377424]]

 [[0.33533243 0.17898657 0.62123666]
  [0.24634741 0.77823862 0.12823722]
  [0.69383049 0.60340122 0.12094132]]

 [[0.49276212 0.32383603 0.47848211]
  [0.49228181 0.52975423 0.80246763]
  [0.88630258 0.64173112 0.95066776]]]


Create a 10x10 array with random values and find the minimum and maximum values

hint: min, max

In [19]:
array = np.random.random((10, 10))
print("Array:")
print(array)

Array:
[[0.77189895 0.67160496 0.13101655 0.14775123 0.14686451 0.77129937
  0.04877411 0.30501978 0.82770181 0.98141738]
 [0.54958529 0.97930743 0.56832707 0.52794994 0.63584694 0.60536641
  0.27238311 0.89569689 0.25558872 0.49348808]
 [0.83947172 0.01701666 0.5872592  0.07349218 0.33794936 0.47377996
  0.09172887 0.09295583 0.33642796 0.17583229]
 [0.4759588  0.42332789 0.86841288 0.90482823 0.77734432 0.42320619
  0.6122642  0.88579332 0.71283659 0.16921882]
 [0.0635744  0.2967281  0.55032646 0.73337778 0.24836158 0.20860698
  0.94105743 0.28506174 0.24395306 0.41975497]
 [0.86662699 0.93986116 0.43867108 0.86760805 0.38577217 0.99795343
  0.42691129 0.77977422 0.27621774 0.78720763]
 [0.06853312 0.44022204 0.95313082 0.50532898 0.51235413 0.9652755
  0.51736013 0.77794231 0.02928857 0.58877428]
 [0.30203043 0.70661437 0.30841059 0.12992956 0.26851373 0.14683843
  0.19337322 0.30638011 0.77965095 0.17159639]
 [0.25271489 0.70936628 0.96318549 0.22954869 0.60783003 0.74406306
  0.49

In [20]:
min_value = np.min(array)
max_value = np.max(array)

print("Minimum value:", min_value)
print("Maximum value:", max_value)

Minimum value: 0.017016662949643213
Maximum value: 0.9979534323333562


 Create a random vector of size 30 and find the mean value

hint: mean

In [21]:
vector = np.random.random(30)

print("Random Vector:")

print(vector)

Random Vector:
[2.19243512e-01 6.29126832e-02 4.06730564e-01 5.70564346e-02
 8.45490783e-01 4.38281823e-01 3.91167245e-02 3.59628904e-01
 2.56357363e-01 5.86502740e-01 1.26505434e-01 2.82912772e-01
 1.77783826e-02 2.98765087e-01 4.69678980e-02 6.26778092e-01
 6.53132158e-04 7.66201279e-02 2.60977189e-01 4.32080582e-01
 7.81647585e-01 5.04828590e-02 2.97373898e-01 3.65581801e-01
 2.08159538e-02 6.35412919e-01 8.97312598e-01 9.43862688e-01
 8.80899830e-01 5.67573580e-01]


In [22]:
mean_value = np.mean(vector)

print("Mean value:", mean_value)

Mean value: 0.3627441312989313


Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 

hint: np.diag

In [27]:
values = [1, 2, 3, 4]
matrix = np.diag(values, k=-1)

print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


Normalize a 5x5 random matrix

hint: (x -mean)/std

In [29]:
matrix = np.random.random((5, 5))

mean = np.mean(matrix)
std = np.std(matrix)

normalized_matrix = (matrix - mean) / std

print(normalized_matrix)


[[-1.23424    -0.55143995  0.40894115  0.5230566   0.416573  ]
 [ 0.60989954  0.18591783  0.9287479  -0.58572083 -0.99968472]
 [-0.85858207  1.30138409  1.08357657 -1.53046961 -1.006811  ]
 [-1.18897885  0.09709136  1.10407387  1.38983056  1.36474036]
 [ 0.7494283  -1.59774939 -1.05837974  1.27658718 -0.82779214]]


How to find common values between two arrays?

hint: np.intersect1d

In [30]:
first_sample = np.array([02.11, 08.30, 02.04])
second_sample = np.array([02.04, 02.11, 02.28])

common_values = np.intersect1d(first_sample, second_sample)

print(common_values)


[2.04 2.11]


Create a random vector of size 10 and sort it

hint: sort

In [31]:
random_vector = np.random.random(10)


sorted_it = np.sort(random_vector)


print(sorted_it)


[0.0280798  0.0531975  0.07145982 0.17677449 0.19325176 0.30418809
 0.49014288 0.53816107 0.58936854 0.770999  ]


Create random vector of size 10 and replace the maximum value by 0

hint: argmax

In [32]:
vector = np.random.rand(10)

print(vector)

[0.59357792 0.3793931  0.09927861 0.92691963 0.45649919 0.77190408
 0.39806052 0.45489959 0.41247763 0.25355223]


In [33]:
max_value = np.argmax(vector)

vector[max_value] = 0

print (vector)

[0.59357792 0.3793931  0.09927861 0.         0.45649919 0.77190408
 0.39806052 0.45489959 0.41247763 0.25355223]


Subtract the mean of each row of a matrix 

hint: mean(axis=,keepdims=)

In [34]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

each_mean = np.mean(matrix, axis=1, keepdims=True)

deducted_matrix = matrix - each_mean

print(deducted_matrix)


[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


How to get the n largest values of an array

Z = np.arange(10000) np.random.shuffle(Z) n = 5 hint: np.argsort | np.argpartition

In [35]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

largest_indices = np.argsort(Z)[-n:]

largest_values = Z[largest_indices]

print(largest_values)


[9995 9996 9997 9998 9999]


Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example: 6 --> 36)

hint: np.where

In [ ]:
import numpy as np

matrix = np.random.randint(0, 10, size=(5, 3))

print("Original Matrix:")
print(matrix)

matrix = np.where(matrix > 4, matrix ** 2, matrix)

print("\nModified Matrix:")
print(matrix)


In [ ]:
import numpy as np

matrix = np.random.randint(0, 10, size=(5, 3))

print("Original Matrix:")
print(matrix)

matrix[matrix > 4] = matrix[matrix > 4] ** 2

print("\nModified Matrix:")
print(matrix)
